In [7]:
import numpy as np

In [9]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
bool_arr = arr>5
bool_arr

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [11]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

# This will perform conditional selection

In [2]:
import jupyterthemes as jt